export const CustomTypography = {
  fontFamily: "Inter",
  "display-3xl-bold": {
    fontSize: "74px",
    lineHeight: "75px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "display-2xl-regular": {
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-2xl-medium": {
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-2xl-semibold": {
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-2xl-bold": {
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "display-xl-regular": {
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },

  "display-xl-medium": {
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-xl-semibold": {
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-xl-bold": {
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 700,

    letterSpacing: "",
  },

  "display-xxxl-bold": {
    fontSize: "54px",
    lineHeight: "75px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "display-xxl-bold": {
    fontSize: "52px",
    lineHeight: "64px",
    fontKerning: "0%",
    fontWeight: 800,
    letterSpacing: "",
  },

  "display-lg-regular": {
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-lg-medium": {
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-lg-semibold": {
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-lg-bold": {
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 700,

    letterSpacing: "",
  },

  "display-md1-regular": {
    fontSize: "40px",
    lineHeight: "31px",
    fontKerning: "0%",
    fontWeight: 400,

    letterSpacing: "",
  },

  "display-md1-semibold": {
    fontSize: "37px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-md-regular": {
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 400,

    letterSpacing: "",
  },
  "display-md-medium": {
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-md-semibold": {
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-md-bold": {
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "display-sm-regular": {
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 400,

    letterSpacing: "",
  },
  "display-sm-medium": {
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-sm-semibold": {
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-sm-bold": {
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "display-md1-medium": {
    fontSize: "28px",
    lineHeight: "31px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },

  "display-sm0-medium": {
    fontSize: "26px",
    lineHeight: "31px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },

  "display-sm1-medium": {
    fontSize: "26px",
    lineHeight: "27px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },

  "display-sm2-medium": {
    fontSize: "26px",
    lineHeight: "27px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },

  "display-xs-regular": {
    fontSize: "24px",
    lineHeight: "40px",
    fontKerning: "0%",
    fontWeight: 400,

    letterSpacing: "",
  },
  "display-xs1-regular": {
    fontSize: "24px",
    lineHeight: "29px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-xs-medium": {
    fontSize: "24px",
    lineHeight: "32px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-xs-semibold": {
    fontSize: "24px",
    lineHeight: "40px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-xs-bold": {
    fontSize: "24px",
    lineHeight: "40px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "display-xs1-bold": {
    fontSize: "24px",
    lineHeight: "34px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "display-xs": {
    fontSize: "22px",
    lineHeight: "48px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-xs-response": {
    fontSize: "20px",
    lineHeight: "32px",
    fontWeight: 300,
    letterSpacing: "",
  },

  "display-xs-response-bold": {
    fontSize: "20px",
    lineHeight: "32px",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xl-regular": {
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },

  "text-xl1-1-regular": {
    fontSize: "20px",
    lineHeight: "34px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },

  "text-xl1-regular": {
    fontSize: "20px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-xl-medium": {
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-xl-semibold": {
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xl-bold": {
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-lg-regular": {
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-lg-medium": {
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-lg-semibold": {
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-lg-bold": {
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 700,

    letterSpacing: "",
  },
  "text-md-regular": {
    fontSize: "16px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-md-medium": {
    fontSize: "16px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-md-semibold": {
    fontSize: "16px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 600,

    letterSpacing: "",
  },
  "text-md-bold": {
    fontSize: "16px",
    lineHeight: "22px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "text-sm-regular": {
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-sm-medium": {
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-sm-semibold": {
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-sm-bold": {
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-sm": {
    fontSize: "13px",
    fontWeight: 400,
    lineHeight: "19.5px",
  },
  "text-xs-small": {
    fontSize: "12px",
    lineHeight: "14px",
    fontKerning: "0%",
    fontWeight: 300,
    letterSpacing: "",
  },
  "text-xs-regular": {
    fontSize: "12px",
    lineHeight: "14px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-xs-regular-color": {
    fontSize: "12px",
    lineHeight: "14px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",

    display: "flex",
    color: "#333333",
    gap: "2px",
  },
  "text-xs-medium": {
    fontSize: "12px",
    lineHeight: "15.6px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-xs0-semibold": {
    fontSize: "12px",
    lineHeight: "12px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xs1-semibold": {
    fontSize: "12px",
    lineHeight: "16px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xs-semibold": {
    fontSize: "12px",
    lineHeight: "15.6px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xs-bold": {
    fontSize: "12px",
    lineHeight: "15.6px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-xxs-small": {
    fontSize: "10px",
    lineHeight: "14px",
    fontKerning: "0%",
    fontWeight: 300,
    letterSpacing: "",
  },
  "text-xs": {
    fontSize: "11px",
    fontWeight: 400,
    lineHeight: "15.4px",
  },
  "text-xxs-medium": {
    fontSize: "10px",
    lineHeight: "12px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-xxs-semi-bold": {
    fontSize: "10px",
    lineHeight: "12px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xxs-bold": {
    fontSize: "10px",
    lineHeight: "26px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-xxs-regular": {
    fontSize: "11px",
    lineHeight: "15.4px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
};
