export const icons = {
  logo: "/Images/logos/main-logo.svg",
  whiteLogo: "/Images/logos/white-logo.svg",
  twitter: "/Images/logos/twitter.svg",
  instagarm: "/Images/logos/instagram.svg",
  facebook: "/Images/logos/facebook.svg",
  uploadLogo: "Images/icons/upload-logo.svg",
  arrowDownIcon: "Images/icons/arrow-down.svg",
  sendSqaureIcon: "Images/icons/send-sqaure.svg",
  printIconIcon: "Images/icons/printer-icon.svg",
  addCircleIcon: "Images/icons/add-circle.svg",
  addCircleOutlinedIcon: "Images/icons/add-circle-outlined.svg",
  tickIcon: "Images/icons/tick-icon.svg",
  colorPickerPaletteIcon: "Images/icons/color-picker-palette-icon.svg",
};
