export const icons = {
  logo: "/Images/logos/main-logo.svg",
  whiteLogo: "/Images/logos/white-logo.svg",
  twitter: "/Images/logos/twitter.svg",
  instagarm: "/Images/logos/instagram.svg",
  facebook: "/Images/logos/facebook.svg",
  youtube: "/Images/logos/youtube.svg",

  youtubeWhiteIcon: "/Images/icons/youtube-white-icon.svg",
  instagramWhiteIcon: "/Images/icons/instagram-white-icon.svg",
  facebookWhiteIcon: "/Images/icons/facebook-white-icon.svg",
  twitterxWhiteIcon: "/Images/icons/twitterx-white-icon.svg",
  linkedinWhiteIcon: "/Images/icons/linkedin-white-icon.svg",

  facebookBlackIcon: "/Images/icons/facebook-black-icon.svg",
  InstagramWhiteIcon: "/Images/icons/instagram-black-icon.svg",

  homeIcon: "/Images/icons/home-line-icon.svg",
  rightArrowIcon: "/Images/icons/right-arrow-icon.svg",

  twitterlpf: "/Images/logos/twitter-lpf.svg",
  facebooklpf: "/Images/logos/facebook-lpf.svg",
  instagarmlpf: "/Images/logos/instagram-lpf.svg",

  uploadLogo: "/Images/icons/upload-logo.svg",
  arrowDownIcon: "/Images/icons/arrow-down.svg",
  sendSqaureIcon: "/Images/icons/send-sqaure.svg",
  printIconIcon: "/Images/icons/printer-icon.svg",
  addCircleIcon: "/Images/icons/add-circle.svg",
  addBlueCircleIcon: "/Images/icons/add-circle-blue.svg",
  addCircleOutlinedIcon: "/Images/icons/add-circle-outlined.svg",
  tickIcon: "/Images/icons/tick-icon.svg",
  editInvoiceNumberIcon: "/Images/icons/edit-invoice-number-icon.svg",
  colorPickerPaletteIcon: "/Images/icons/color-picker-palette-icon.svg",
  invoiceIcon: "/Images/icons/invoice-icon.svg",
  clientsIcon: "/Images/icons/clients-icon.svg",
  settingsIcon: "/Images/icons/settings-icon.svg",
  firstInvoiceIcon: "/Images/icons/crt-first-invoice-icon.svg",
  searchIcon: "/Images/icons/search-icon.svg",
  filterIcon: "/Images/icons/filter-icon.svg",
  plusIcon: "/Images/icons/plus-icon.svg",
  threeDotsIcon: "/Images/icons/three-dots-icon.svg",
  editIcon: "/Images/icons/edit-icon.svg",
  profileIcon: "/Images/icons/profile-icon.svg",
  logoutIcon: "/Images/icons/logout-icon.svg",
  viewIcon: "/Images/icons/view-icon.svg",
  pdfPriviewIcon: "/Images/icons/pdg-priview-icon.svg",
  deleteIcon: "/Images/icons/delete-icon.svg",
  deleteRedIcon: "/Images/icons/delete-red-icon.svg",
  watermarkIcon: "/Images/icons/watermark-icon.svg",
  copyIcon: "/Images/icons/copy-icon.svg",
  whatsappIcon: "/Images/icons/whatsapp-icon.svg",
  facebookIcon: "/Images/icons/facebook-icon.svg",
  twitterIcon: "/Images/icons/twitter-icon.svg",
  personIcon: "/Images/icons/person-icon.svg",
  cameraIcon: "/Images/icons/camera-icon.svg",
  editWhiteIcon: "/Images/icons/edit-white-icon.svg",
  openEyeIcon: "/Images/icons/open-eye-icon.svg",
  closeEyeIcon: "/Images/icons/close-eye-icon.svg",
  sortIcon: "/Images/icons/sort-icon.svg",
  easyUseIcon: "/Images/icons/easy-use-icon.svg",
  customColorIcon: "/Images/icons/custom-color-icon.svg",
  freeGenerateIcon: "/Images/icons/free-generate-icon.svg",

  educationIcon: "/Images/icons/education-icon.svg",
  fitnessIcon: "/Images/icons/fitness-icon.svg",
  beautyIcon: "/Images/icons/beauty-icon.svg",
  officialsIcon: "/Images/icons/officials-icon.svg",
  medicalIcon: "/Images/icons/medical-icon.svg",
  eventsIcon: "/Images/icons/events-icon.svg",
  plusCircleIcon: "/Images/icons/plus-circle-icon.svg",
  minusCircleIcon: "/Images/icons/minus-circle-icon.svg",
  emailIcon: "/Images/icons/mail-icon.svg",
  markerPinIcon: "/Images/icons/marker-pin-icon.svg",
  PhoneIcon: "/Images/icons/phone-icon.svg",
  FooterPhoneIcon: "/Images/icons/footer-phone-icon.svg",
  FooterMailIcon: "/Images/icons/footer-mail-icon.svg",
  FooterMarkerIcon: "/Images/icons/footer-marker-icon.svg",

  navigationPinterIcon: "/Images/icons/navigation-pointer-icon.svg",
  handShakePurpleIcon: "/Images/icons/business-2-icon.svg",
  handShakeWhiteIcon: "/Images/icons/business-2-1-icon.svg",
  ecommerceWhiteIcon: "/Images/icons/business-3-1-icon.svg",
  ecommercePurpoleIcon: "/Images/icons/business-3-icon.svg",
  arrowDownBlueIcon: "/Images/icons/arrow-down-blue-icon.svg",
  arrowDownUpIcon: "/Images/icons/arrow-up-blue-icon.svg",
  facebook1Icon: "/Images/icons/facebook1-icon.svg",
  instagram1Icon: "/Images/icons/instagram1-icon.svg",
  youtube1Icon: "/Images/icons/youtube1-icon.svg",
  twittter1Icon: "/Images/icons/twitter1-icon.svg",
  linkedin1Icon: "/Images/icons/linkedin1-icon.svg",
  twitterxDarkIcon: "/Images/icons/twitterx-dark-icon.svg",
  twitterxIcon: "/Images/icons/twitterx-icon.svg",

  contactLocationIcon: "/Images/icons/contact-location-icon.svg",
  contactWhiteLocationIcon: "/Images/icons/contact-location-white-icon.svg",
  contactPhoneIcon: "/Images/icons/contact-phone-icon.svg",
  contactWhitePhoneIcon: "/Images/icons/contact-phone-white-icon.svg",
  contactMailIcon: "/Images/icons/contact-mail-icon.svg",
  contactWhiteMailIcon: "/Images/icons/contact-mail-white-icon.svg",

  tickBageIcon: "/Images/about/icons/tick-bage.svg",
  tickBageWhiteIcon: "/Images/about/icons/tick-bage-white-icon.svg",

  tickPersonIcon: "/Images/about/icons/tick-person-icon.svg",
  tickPersonWhiteIcon: "/Images/about/icons/tick-person-white-icon.svg",

  searchBoxIcon: "/Images/about/icons/search-box-icon.svg",
  searchBoxWhiteIcon: "/Images/about/icons/search-box-white-icon.svg",

  perpleWorldLinedIcon: "/Images/about/icons/perple-world-lined-icon.svg",
  whiteWorldLinedIcon: "/Images/about/icons/white-world-lined-icon.svg",
};

export const backendURL =
  process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:3005";

export const frontendUrl =
  process.env.NEXT_PUBLIC_GOOGLE_CALLBACK_URL ||
  "https://main.d33zziho5sqnl9.amplifyapp.com";
