name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  API_GATEWAY_STAGE: main

jobs:
  deploy:
    name: Build and deploy dev Docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.PROD_ENV }}
          EOF
      - name: Docker build
        run: docker build -t frontend-prod .
        
      - name: Docker stop and remove
        run: |
          CONTAINER_NAME="frontend-prod-c"
          if [[ "$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME 2>/dev/null)" == "true" ]]; then
            echo "Stopping Docker container $CONTAINER_NAME"
            docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME && sudo docker system prune -f
          else
            echo "Docker container $CONTAINER_NAME is not running"
          fi
      
      - name: Docker start 
        run: docker run -d --name frontend-prod-c -p 3002:3000 frontend-prod

      - name: Docker show logs 
        run: sleep 50 && docker logs frontend-prod-c

      - name: Clean up interim Docker
        run: docker image prune -f && docker container prune -f

  # notify_slack_success:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   if: success()
  #   steps:
  #     - name: Notify in Slack on success
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: deployment_alerts
  #         SLACK_WEBHOOK: https://hooks.slack.com/services/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
  #         SLACK_COLOR: good
  #         SLACK_MESSAGE: '🚀 Deployment successful! Our updates are now live. Let’s continue monitoring for any feedback.'
  #         SLACK_AUTHOR: ${{ github.actor }}

  # notify_slack_failure:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   if: failure()
  #   steps:
  #     - name: Notify in Slack on failure
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: deployment_alerts
  #         SLACK_WEBHOOK: https://hooks.slack.com/services/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
  #         SLACK_COLOR: danger
  #         SLACK_MESSAGE: '🚫 Deployment failed. Please check the logs for details and let’s investigate the issue.'
  #         SLACK_AUTHOR: ${{ github.actor }}
