name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  API_GATEWAY_STAGE: main

jobs:
  deploy:
    name: Build and deploy dev Docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.STG_ENV }}
          EOF
      - name: Docker build
        run: docker build -t frontend-stg .
        
      - name: Docker stop and remove
        run: |
          CONTAINER_NAME="frontend-stg-c"
          if [[ "$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME 2>/dev/null)" == "true" ]]; then
            echo "Stopping Docker container $CONTAINER_NAME"
            docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME && sudo docker system prune -f
          else
            echo "Docker container $CONTAINER_NAME is not running"
          fi
      
      - name: Docker start 
        run: docker run -d --name frontend-stg-c -p 3002:3000 frontend-stg

      - name: Docker show logs 
        run: sleep 50 && docker logs frontend-stg-c

      - name: Clean up interim Docker
        run: docker image prune -f && docker container prune -f

  notify_slack_success:
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Notify in Slack on success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alerts-deployment
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_COLOR: good
          SLACK_MESSAGE: 'Web staging deployment successful :tada:'
          SLACK_AUTHOR: ${{ github.actor }}

  notify_slack_failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Notify in Slack on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alerts-deployment
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'Web staging deployment failed :x:'
          SLACK_AUTHOR: ${{ github.actor }}
