name: Deploy qa branch

on:
  push:
    branches:
      - qa

env:
  API_GATEWAY_STAGE: qa

jobs:
  deploy:
    name: Build and deploy prod Docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.QA_ENV }}
          EOF
      - name: Docker build
        run: docker build -t frontend-qa .
        
      - name: Docker stop and remove
        run: |
          CONTAINER_NAME="frontend-qa-c"
          if [[ "$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME 2>/dev/null)" == "true" ]]; then
            echo "Stopping Docker container $CONTAINER_NAME"
            docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME && sudo docker system prune -f
          else
            echo "Docker container $CONTAINER_NAME is not running"
          fi
      
      - name: Docker start 
        run: docker run -d --name frontend-qa-c -p 3001:3000 frontend-qa

      - name: Docker show logs 
        run: sleep 50 && docker logs frontend-qa-c

      - name: Clean up interim Docker
        run: docker image prune -f && docker container prune -f
  notify_slack_success:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ success() }}
    steps:
      - name: Notify in Slack on success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alerts-deployment
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_COLOR: good
          SLACK_MESSAGE: 'The deployment of the *qa branch* to the development environment has completed successfully :rocket:. All services are running smoothly. Triggered by *${{ github.actor }}*.'
          SLACK_AUTHOR: ${{ github.actor }}
          DEBUG: true  # Enable debug logging for Slack action

  notify_slack_failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ failure() }}
    steps:
      - name: Notify in Slack on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alerts-deployment
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_COLOR: danger
          SLACK_MESSAGE: ':warning: *Deployment failed*: The deployment of the *dev branch* to the development environment was unsuccessful :x:. Initiated by *${{ github.actor }}*. Please check the logs and take appropriate action.'
          SLACK_AUTHOR: ${{ github.actor }}
          DEBUG: true  # Enable debug logging for Slack action

 
