name: Deploy main branch

on:
  push:
    branches:
      - qa

env:
  API_GATEWAY_STAGE: prod

jobs:
  deploy:
    name: Build and deploy prod Docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.PROD_ENV }}
          EOF
      - name: Docker build
        run: docker build -t frontend-prod .
        
      - name: Docker stop and remove
        run: |
          CONTAINER_NAME="frontend-prod-c"
          if [[ "$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME 2>/dev/null)" == "true" ]]; then
            echo "Stopping Docker container $CONTAINER_NAME"
            docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME && sudo docker system prune -f
          else
            echo "Docker container $CONTAINER_NAME is not running"
          fi
      
      - name: Docker start 
        run: docker run -d --name frontend-prod-c -p 3002:3000 frontend-prod

      - name: Docker show logs 
        run: sleep 50 && docker logs frontend-prod-c

      - name: Clean up interim Docker
        run: docker image prune -f && docker container prune -f

 
